language: csharp
dist: trusty
sudo: required
before_install:
  - chmod +x build.sh
mono: none
dotnet: 2.0.3 # https://www.microsoft.com/net/download/linux
branches:
  only:
    - master
    - develop
script:
  - ./build.sh
before_deploy:
   # Set up git user name and tag this commit
  - git config --local user.name "Renan Marcel Paulino Leite"
  - git config --local user.email "renan.leite@globo.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: GitHub
  tag: v$(appveyor_build_version)
  release: v$(appveyor_build_version)
  auth_token:
    secure: 4321c3669a6821d78eb3758b831fe3f5acc8d1e4
  file_glob: true
  file: artifacts/**/*
  skip_cleanup: true
  on:
    branch: master
